name: 'Base setup'
description: 'Checkout and setup jdk / sbt with caching'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Cache sbt and ivy dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2 # AdoptOpenJDK
      with:
        java-version: 8
