name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/base
      - name: scalafmt
        run: sbt scalafmtCheckAll

  build:
    needs: fmt
    strategy:
      matrix:
        scala: [2.12.12, 2.13.3]

    runs-on: ubuntu-latest

    steps:
      - uses: ./github/actions/base
      - name: Compile
        run: sbt ++${{matrix.scala}} compile test:compile it:compile
      - name: Run unit tests
        run: sbt -J-Xmx2G ++${{matrix.scala}} test

  it:
    needs: fmt

    runs-on: ubuntu-latest

    steps:
      - uses: ./github/actions/base
      - name: Run Integration Tests
        run: sbt -J-Xmx2G it:test
