name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2 # AdoptOpenJDK
        with:
          java-version: 8
      - name: Cache sbt and ivy dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: scalafmt
        run: sbt scalafmtCheckAll

  build:
    needs: fmt
    strategy:
      matrix:
        scala: [2.12.12, 2.13.3]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2 # AdoptOpenJDK
        with:
          java-version: 8
      - name: Cache sbt and ivy dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt ++${{matrix.scala}} compile test:compile it:compile
      - name: Run unit tests
        run: sbt -J-Xmx2G ++${{matrix.scala}} test

  it:
    needs: fmt

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2 # AdoptOpenJDK
        with:
          java-version: 8
      - name: Cache sbt and ivy dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Integration Tests
        run: sbt -J-Xmx2G it:test
