name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2 # AdoptOpenJDK
        with:
          java-version: 8
      - name: Cache sbt and ivy dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: scalafmt
        run: sbt scalafmtCheckAll

  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: fmt
    strategy:
      matrix:
        scala: [2.12.12, 2.13.3]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2 # AdoptOpenJDK
        with:
          java-version: 8
      - name: Cache sbt and ivy dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt ++${{matrix.scala}} compile test:compile it:compile
      - name: Run unit tests
        run: sbt -J-Xmx2G ++${{matrix.scala}} coverage test coverageReport
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit-scala-${{matrix.scala}}
          fail_ci_if_error: true
          verbose: false

  it:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: fmt
    strategy:
      matrix:
        postgres: [13, 12, 11, 10, 9]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2 # AdoptOpenJDK
        with:
          java-version: 8
      - name: Cache sbt and ivy dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Integration Tests
        env:
          POSTGRES_VERSION: ${{matrix.postgres}}
        run: sbt -J-Xmx2G coverage it:test coverageReport
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integrationt-pg-${{matrix.postgres}}
          fail_ci_if_error: true
          verbose: false
